Repository cal-itp/littlepay, pull requests merged in 2024-04, with the labels that each got.

#23 Fix: separate scrape and commit jobs
  .github/workflows/scrape.yml
  data/mst_groups.csv
  data/mst_linked_groups_products.csv
  data/mst_products.csv
  data/sacrt_groups.csv
  data/sacrt_linked_groups_products.csv
  data/sacrt_products.csv
  data/sbmtd_groups.csv
  data/sbmtd_linked_groups_products.csv
  data/sbmtd_products.csv
Labels: bug, actions

#49 Feat: command for group migration
  littlepay/commands/groups.py
  littlepay/main.py
  tests/commands/test_groups.py
  tests/test_main.py
Labels: cli

#52 Chore: manifest file to exclude from source build
  MANIFEST.in
Labels: chore

#55 Feat: command to list group funding sources
  littlepay/commands/groups.py
  littlepay/main.py
  tests/commands/test_groups.py
  tests/test_main.py
Labels: cli

#59 docs: add new group commands
  README.md
Labels: documentation
